<Project Sdk="Microsoft.Build.NoTargets">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;netcoreapp2.0;netcoreapp2.1;netcoreapp3.0;netcoreapp3.1;net5.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>
  
    <ItemGroup>
      <ProjectReference Include="getPrune\getPrune.csproj" />
      <ProjectReference Include="getRef\getRef.csproj" />
    </ItemGroup>

    <Target Name="Test" AfterTargets="Compile">
      <ItemGroup>
        <TestFile Include="getPrune\bin\Debug\$(TargetFramework)\References\*.dll" />
        <TestFile CompareTo="getRef\bin\Debug\$(TargetFramework)\References\%(FileName)%(Extension)" />

        <MissingFile Include="@(TestFile)" Condition="!Exists('%(TestFile.CompareTo)')" />
        <ExistingFile Include="@(TestFile)" Condition="Exists('%(TestFile.CompareTo)')" />
      </ItemGroup>

      <WriteLinesToFile
        File="MissingFiles_$(TargetFramework).log"
        Lines="@(MissingFile->'%(Identity)')"
        Overwrite="true" />

      <WriteLinesToFile 
        File="$(TargetDir)apiCompat.rsp"
        Lines="@(ExistingFile->'-l %(Identity) -r %(CompareTo)');
               --lref getRef\bin\Debug\$(TargetFramework)\References
               --rref getRef\bin\Debug\$(TargetFramework)\References
               --suppression-output-file apicompat_$(TargetFramework).xml
               --generate-suppression-file"
        Overwrite="true" /> 

        <Exec Command="apicompat @$(TargetDir)apiCompat.rsp" />
    </Target>
</Project>
