<Project Sdk="Microsoft.Build.NoTargets">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;netcoreapp2.0;netcoreapp2.1;netcoreapp3.0;netcoreapp3.1;net5.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>
  
    <ItemGroup>
      <ProjectReference Include="getPrune\getPrune.csproj" />
      <ProjectReference Include="getRef\getRef.csproj" />
    </ItemGroup>

    <PropertyGroup>
      <!-- Missing dependency -->
      <ApiCompatNoWarn>CP1002</ApiCompatNoWarn>
      <!-- Changing generic constraint -->
      <ApiCompatNoWarn>$(ApiCompatNoWarn);CP0021</ApiCompatNoWarn>
      <!-- Remove virtual - https://github.com/dotnet/sdk/issues/50671 -->
      <ApiCompatNoWarn>$(ApiCompatNoWarn);CP0012</ApiCompatNoWarn>
      <!-- Sealing type -->
      <ApiCompatNoWarn>$(ApiCompatNoWarn);CP0009</ApiCompatNoWarn>

      <MissingFileSeparator>
.
------------------- NuGet Dependency Graphs -------------------
.
      </MissingFileSeparator>
    </PropertyGroup>

    <Target Name="Test" AfterTargets="Compile">
      <ItemGroup>
        <TestFile Include="getPrune\bin\Debug\$(TargetFramework)\References\*.dll" />
        <TestFile Original="%(Identity)" CompareTo="getRef\bin\Debug\$(TargetFramework)\References\%(FileName)%(Extension)" />
        <TestFileByName Include="@(TestFile->'%(FileName)')" />        

        <MissingFile Include="@(TestFileByName)" Condition="!Exists('%(CompareTo)')" />
        <ExistingFile Include="@(TestFileByName)" Condition="Exists('%(CompareTo)')" />

        <!-- Remove NetFx facades from API Compat testing -->
        <ExistingFile Remove="mscorlib;System;System.Core;System.Configuration;System.Data;System.Drawing;System.Net;System.Security;System.ServiceProcess;System.Transactions;WindowsBase" />

        <ExistingFile ApiCompatCommand="-l %(ExistingFile.Original) -r %(ExistingFile.CompareTo)
               --lref getRef\bin\Debug\$(TargetFramework)\References
               --rref getRef\bin\Debug\$(TargetFramework)\References
               --suppression-output-file Results\$(TargetFramework)\apicompat_%(ExistingFile.Identity).xml
               --generate-suppression-file
               --noWarn $([MSBuild]::Escape('$(ApiCompatNoWarn)'))"
               ApiCompatRspFile="$(TargetDir)apiCompat_%(ExistingFile.Identity).rsp" />
      </ItemGroup>

      <MakeDir Directories="Results\$(TargetFramework)" />

      <WriteLinesToFile
        File="Results\$(TargetFramework)\MissingFiles.txt"
        Lines="@(MissingFile);$(MissingFileSeparator)"
        Condition="@(MissingFile) != ''" 
        Overwrite="true" />

      <Exec Command="dotnet nuget why getPrune\getPrune.csproj %(MissingFile.Identity) -f $(TargetFramework) >> Results\$(TargetFramework)\MissingFiles.txt" 
            Condition="@(MissingFile) != ''" />

      <WriteLinesToFile 
        File="%(ExistingFile.ApiCompatRspFile)"
        Lines="%(ExistingFile.ApiCompatCommand)"
        Overwrite="true" />

      <Exec Command="apicompat @%(ExistingFile.ApiCompatRspFile)" Condition="'$(RunApiCompat)' != 'false'" />
    </Target>
</Project>
