<Project Sdk="Microsoft.Build.NoTargets">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;netcoreapp2.0;netcoreapp2.1;netcoreapp3.0;netcoreapp3.1;net5.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>
  
    <ItemGroup>
      <ProjectReference Include="getPrune\getPrune.csproj" Targets="CopyReferences" ReferenceOutputAssembly="false" OutputItemType="TestFile" />
      <ProjectReference Include="getRef\getRef.csproj"  Targets="CopyReferences" ReferenceOutputAssembly="false" OutputItemType="RefFile" />
    </ItemGroup>

    <PropertyGroup>
      <!-- Missing dependency -->
      <ApiCompatNoWarn>CP1002</ApiCompatNoWarn>
      <!-- Changing generic constraint -->
      <ApiCompatNoWarn>$(ApiCompatNoWarn);CP0021</ApiCompatNoWarn>
      <!-- Remove virtual - https://github.com/dotnet/sdk/issues/50671 -->
      <ApiCompatNoWarn>$(ApiCompatNoWarn);CP0012</ApiCompatNoWarn>
      <!-- Sealing type -->
      <ApiCompatNoWarn>$(ApiCompatNoWarn);CP0009</ApiCompatNoWarn>

      <MissingFileSeparator>
.
------------------- NuGet Dependency Graphs -------------------
.
      </MissingFileSeparator>
    </PropertyGroup>

    <Target Name="TestMissingFiles">
      <ItemGroup>      
        <TestFileByName Include="@(TestFile->'%(FileName)')" Original="%(Identity)" />
        <RefFileByName Include="@(RefFile->'%(FileName)')" />
        <MissingFileByFileName Include="@(TestFileByName)" Exclude="@(RefFileByName)" />
        <ExistingFileByFileName Include="@(TestFileByName)" Exclude="@(MissingFileByFileName)" />
        <!-- Skip NetFx facades from API Compat testing -->
        <ExistingFileByFileName Remove="mscorlib;System;System.Core;System.Configuration;System.Data;System.Drawing;System.Net;System.Security;System.ServiceProcess;System.Transactions;WindowsBase" />
        <ExistingFile Include="@(ExistingFileByFileName->'%(Original)')" />
      </ItemGroup>      

      <RemoveDir Directories="Results\$(TargetFramework)" />
      <MakeDir Directories="Results\$(TargetFramework)" />

      <WriteLinesToFile
        File="Results\$(TargetFramework)\MissingFiles.txt"
        Lines="@(MissingFileByFileName);$(MissingFileSeparator)"
        Condition="@(MissingFileByFileName) != ''" 
        Overwrite="true" />

      <Exec Command="dotnet nuget why getPrune\getPrune.csproj %(MissingFileByFileName.Identity) -f $(TargetFramework) >> Results\$(TargetFramework)\MissingFiles.txt" 
            Condition="@(MissingFileByFileName) != ''" />
    </Target>

    <Target Name="CompareExistingFile"
            Inputs="%(ExistingFile.FileName)"
            Outputs="unused"
            DependsOnTargets="TestMissingFiles"
            Condition="'@(ExistingFile)' != ''">
      <PropertyGroup>
        <_fileName>%(ExistingFile.FileName)</_fileName>
      </PropertyGroup>
      <ItemGroup>
        <MatchingRefFile Include="@(RefFile->WithMetadataValue('FileName', '$(_fileName)'))" />
      </ItemGroup>
      <PropertyGroup>
        <Refpath>%(MatchingRefFile.RootDir)%(MatchingRefFile.Directory)</Refpath>
        <ApiCompatSuppressionFile>Results\$(TargetFramework)\apicompat_%(ExistingFile.FileName).xml</ApiCompatSuppressionFile>
        <ApiCompatRspFile>$(TargetDir)apiCompat_%(ExistingFile.FileName).rsp</ApiCompatRspFile>
        <ApiCompatCommand>
          -l @(ExistingFile) -r @(MatchingRefFile)
          --lref $(Refpath)
          --rref $(Refpath)
          --left-assemblies-transformation-pattern $([MSBuild]::Escape('.+\\([^\\]+\.dll);pruned/$1'))
          --right-assemblies-transformation-pattern $([MSBuild]::Escape('.+\\([^\\]+\.dll);framework/$1'))
          --suppression-output-file $(ApiCompatSuppressionFile)
          --generate-suppression-file
          --noWarn $([MSBuild]::Escape('$(ApiCompatNoWarn)'))
        </ApiCompatCommand>
        <TestAssemblyVersion>$([System.Text.RegularExpressions.Regex]::Replace('%(ExistingFile.FusionName)', '^.*Version=([0-9\.]+).*$', '$1'))</TestAssemblyVersion>
        <RefAssemblyVersion>$([System.Text.RegularExpressions.Regex]::Replace('%(MatchingRefFile.FusionName)', '^.*Version=([0-9\.]+).*$', '$1'))</RefAssemblyVersion>
      </PropertyGroup>

      <WriteLinesToFile File="Results\$(TargetFramework)\VersionFiles.txt"
                        Lines="%(ExistingFile.FileName) $(TestAssemblyVersion) is greater than $(RefAssemblyVersion)" 
                        Condition="$([MSBuild]::VersionGreaterThan('$(TestAssemblyVersion)', '$(RefAssemblyVersion)'))" />

      <WriteLinesToFile File="$(ApiCompatRspFile)" Lines="$(ApiCompatCommand)" Overwrite="true" />

      <Exec Command="apicompat @$(ApiCompatRspFile)" Condition="'$(RunApiCompat)' != 'false'" />

    </Target>

    <Target Name="Test" AfterTargets="Compile" DependsOnTargets="TestMissingFiles;CompareExistingFile" />
</Project>
