<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Pruning data has some downgrades -->
    <NoWarn>$(NoWarn);NU1605</NoWarn>
    <AspNet2Version>2.3.*</AspNet2Version>
  </PropertyGroup>

  <UsingTask TaskName="GetPackagesToPrune" AssemblyFile="C:\src\dotnet\sdk\artifacts\bin\Sdks\Microsoft.NET.Sdk\tools\net10.0\Microsoft.NET.Build.Tasks.dll" />

  <Target Name="RemoveFrameworkReferences" BeforeTargets="ResolveFrameworkReferences">
    <ItemGroup>
      <FrameworkReference Remove="@(FrameworkReference)" />
    </ItemGroup>
  </Target>

  <!-- Don't bring in any framework references, instead reference every package in the pruning list -->
  <Target Name="AddPackageReferences" BeforeTargets="CollectPrunePackageReferences"
          DependsOnTargets="ProcessFrameworkReferences">

    <PropertyGroup>
      <PrunePackageDataRoot Condition="'$(PrunePackageDataRoot)' == ''">$(NetCoreRoot)\sdk\$(NETCoreSdkVersion)\PrunePackageData\</PrunePackageDataRoot>
      <PrunePackageTargetingPackRoots Condition="'$(PrunePackageTargetingPackRoots)' == ''">$(NetCoreTargetingPackRoot)</PrunePackageTargetingPackRoots>
      <AllowMissingPrunePackageData Condition="'$(AllowMissingPrunePackageData)' == ''">false</AllowMissingPrunePackageData>
    </PropertyGroup>
    
    <GetPackagesToPrune TargetFrameworkIdentifier="$(TargetFrameworkIdentifier)"
                        TargetFrameworkVersion="$(_TargetFrameworkVersionWithoutV)"
                        FrameworkReferences="@(FrameworkReference)"
                        TargetingPacks="@(TargetingPack)"
                        TargetingPackRoots="$(PrunePackageTargetingPackRoots)"
                        PrunePackageDataRoot="$(PrunePackageDataRoot)"
                        AllowMissingPrunePackageData="$(AllowMissingPrunePackageData)">
      <Output TaskParameter="PackagesToPrune" ItemName="_PackageReference" />
    </GetPackagesToPrune>

    <ItemGroup>
      <PackageReference Include="%(_PackageReference.Identity)" Version="$([System.String]::new('%(_PackageReference.Version)').Replace('32767', '*'))" IncludeAssets="Compile" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Condition="'%(PackageReference.Version)' == '10.0.*'" Version="10.0.0-*" />
    </ItemGroup>

    <!-- We have some imaginary version in net9.0 & 10.0 -->
    <ItemGroup Condition="'$(TargetFramework)' == 'net10.0' or '$(TargetFramework)' == 'net9.0'"  >
      <PackageReference Condition="'%(Identity)' == 'System.Xml.XPath.XDocument'" Version="4.*" />
      <PackageReference Condition="'%(Identity)' == 'Microsoft.VisualBasic'" Version="10.*" />
      <PackageReference Condition="'%(Identity)' == 'System.Buffers'" Version="4.*" />
      <PackageReference Condition="'%(Identity)' == 'System.Memory'" Version="4.*" />
      <PackageReference Condition="'%(Identity)' == 'System.Numerics.Vectors'" Version="4.*" />
      <PackageReference Condition="'%(Identity)' == 'System.Reflection.DispatchProxy'" Version="4.*" />
      <PackageReference Condition="'%(Identity)' == 'System.Runtime.CompilerServices.Unsafe'" Version="6.*" />
      <PackageReference Condition="'%(Identity)' == 'System.Threading.Tasks.Extensions'" Version="4.*" />
      <PackageReference Remove="System.Formats.Tar" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'">
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Antiforgery'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Authentication.Abstractions'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Authentication.Cookies'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Authentication.Core'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Authentication'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Authentication.OAuth'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Authorization.Policy'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.CookiePolicy'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Cors'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Diagnostics.Abstractions'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Diagnostics'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Diagnostics.HealthChecks'" Version="2.2.0" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.HostFiltering'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Hosting.Abstractions'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Hosting'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Hosting.Server.Abstractions'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Html.Abstractions'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Http.Abstractions'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Http.Connections'" Version="1.2.0" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Http'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Http.Extensions'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Http.Features' AND  $([MSBuild]::VersionGreaterThan('$(TargetFrameworkVersion)', '5.0'))" Version="5.0.*" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.HttpOverrides'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.HttpsPolicy'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Identity'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Localization'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Localization.Routing'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Mvc.Abstractions'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Mvc.ApiExplorer'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Mvc.Core'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Mvc.Cors'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Mvc.DataAnnotations'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Mvc'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Mvc.Formatters.Json'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Mvc.Formatters.Xml'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Mvc.Localization'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Mvc.Razor'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Mvc.RazorPages'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Mvc.TagHelpers'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Mvc.ViewFeatures'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Razor'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Razor.Runtime'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.ResponseCaching.Abstractions'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.ResponseCaching'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.ResponseCompression'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Rewrite'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Routing.Abstractions'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Routing'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Server.HttpSys'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Server.IIS'" Version="2.2.6" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Server.IISIntegration'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Server.Kestrel.Core'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Server.Kestrel'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.Session'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.SignalR.Core'" Version="1.2.0" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.SignalR'" Version="1.2.0" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.StaticFiles'" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.WebSockets'" Version="$(AspNet2Version)" />
      
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.Net.Http.Headers' AND  $([MSBuild]::VersionLessThan('$(TargetFrameworkVersion)', '8.0'))" Version="$(AspNet2Version)" />
      <PackageReference  Condition="'%(Identity)' == 'Microsoft.AspNetCore.WebUtilities' AND  $([MSBuild]::VersionLessThan('$(TargetFrameworkVersion)', '8.0'))" Version="$(AspNet2Version)" />

      <PackageReference Remove="Microsoft.AspNetCore.Components.Server" />
      <PackageReference Remove="Microsoft.AspNetCore.StaticAssets" />
      <PackageReference Remove="Microsoft.AspNetCore.RateLimiting" />
      <PackageReference Remove="Microsoft.AspNetCore.Http.Results" />
      <PackageReference Remove="Microsoft.AspNetCore.HttpLogging" />
      <PackageReference Remove="Microsoft.AspNetCore.OutputCaching" />
      <PackageReference Remove="Microsoft.AspNetCore.RequestDecompression" />
      <PackageReference Remove="Microsoft.AspNetCore.Authentication.BearerToken" />
      <PackageReference Remove="Microsoft.AspNetCore.Components.Endpoints" />
      <PackageReference Remove="Microsoft.AspNetCore.Server.Kestrel.Transport.NamedPipes" />
      <PackageReference Remove="Microsoft.AspNetCore.Server.Kestrel.Transport.Quic" />

      <!-- Meta packages -->
      <PackageReference Remove="Microsoft.AspNetCore.App" />
      <PackageReference Remove="Microsoft.AspNetCore" />
    </ItemGroup>
  
  </Target>
</Project>
